// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-u-Fa0cT8PWWVzHEl-Vf42mKr59votlE',
    appId: '1:646115284403:web:95489fd0d87811da1da7c6',
    messagingSenderId: '646115284403',
    projectId: 'recipe-app-9c08c',
    authDomain: 'recipe-app-9c08c.firebaseapp.com',
    storageBucket: 'recipe-app-9c08c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsMr1RfnC1nZK3hTLY_TrG9Hblbc6r-fg',
    appId: '1:646115284403:android:c2a4cebe1a24cd421da7c6',
    messagingSenderId: '646115284403',
    projectId: 'recipe-app-9c08c',
    storageBucket: 'recipe-app-9c08c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVUasG5-jDSA56iww7fg23fwlR9-TNPGw',
    appId: '1:646115284403:ios:b8b21cc12ca1cdc41da7c6',
    messagingSenderId: '646115284403',
    projectId: 'recipe-app-9c08c',
    storageBucket: 'recipe-app-9c08c.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVUasG5-jDSA56iww7fg23fwlR9-TNPGw',
    appId: '1:646115284403:ios:eb56bdaba0422d461da7c6',
    messagingSenderId: '646115284403',
    projectId: 'recipe-app-9c08c',
    storageBucket: 'recipe-app-9c08c.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
